### ISSUE TITLE
Error when using with Spongeforge

### ISSUE THREAD

**Issue by kuhler-Stratege** [MrTrollNugNug/Rope-Bridge#37] opened 2020-09-13 19:15 UTC
Hello,
I am running a 1.12 server and have spongeforge and your rope brigde mod installed. If I now want to place a bridge, Sponge blocks it and says:
**/**************************************************************************************************************/
[21:06:43] [Timer-1229/ERROR] [Sponge]: /*                                         Illegal Async Block Change                                         */
[21:06:43] [Timer-1229/ERROR] [Sponge]: /**************************************************************************************************************/
[21:06:43] [Timer-1229/ERROR] [Sponge]: /* Sponge adapts the vanilla handling of                                                                      */
[21:06:43] [Timer-1229/ERROR] [Sponge]: /* block changes to power events and                                                                          */
[21:06:43] [Timer-1229/ERROR] [Sponge]: /* plugins such that it follows the known                                                                     */
[21:06:43] [Timer-1229/ERROR] [Sponge]: /* fact that block changes MUST occur on                                                                      */
[21:06:43] [Timer-1229/ERROR] [Sponge]: /* the server thread (even on clients, this                                                                   */
[21:06:43] [Timer-1229/ERROR] [Sponge]: /* exists as the InternalServer thread). It                                                                   */
[21:06:43] [Timer-1229/ERROR] [Sponge]: /* is NOT possible to change this fact and                                                                    */
[21:06:43] [Timer-1229/ERROR] [Sponge]: /* must be reported to the offending mod                                                                      */
[21:06:43] [Timer-1229/ERROR] [Sponge]: /* for async issues.                                                                                          */
[21:06:43] [Timer-1229/ERROR] [Sponge]: /*                                                                                                            */
[21:06:43] [Timer-1229/ERROR] [Sponge]: /*  World : WorldServer{Name=J und J Serverwelt, DimensionId=0, DimensionType=minecraft:overworld}            */
[21:06:43] [Timer-1229/ERROR] [Sponge]: /*  Block Pos : -307, 85, 62                                                                                  */
[21:06:43] [Timer-1229/ERROR] [Sponge]: /*  BlockState : ropebridge:bridge_block_2[back=0,front=0,rotated=true,type=big_oak]                          */
[21:06:43] [Timer-1229/ERROR] [Sponge]: /*                                                                                                            */
[21:06:43] [Timer-1229/ERROR] [Sponge]: /* Sponge is not going to allow this block                                                                    */
[21:06:43] [Timer-1229/ERROR] [Sponge]: /* change to take place as doing so can                                                                       */
[21:06:43] [Timer-1229/ERROR] [Sponge]: /* lead to further issues, not just with                                                                      */
[21:06:43] [Timer-1229/ERROR] [Sponge]: /* sponge or plugins, but other mods as                                                                       */
[21:06:43] [Timer-1229/ERROR] [Sponge]: /* well.                                                                                                      */
[21:06:43] [Timer-1229/ERROR] [Sponge]: /*                                                                                                            */
[21:06:43] [Timer-1229/ERROR] [Sponge]: /*     java.lang.Exception: Async Block                                                                       */
[21:06:43] [Timer-1229/ERROR] [Sponge]: /*     Change Detected                                                                                        */
[21:06:43] [Timer-1229/ERROR] [Sponge]: /*     org.spongepowered.common.event.tracking.PhaseTracker.setBlockState(PhaseTracker.java:842)              */
[21:06:43] [Timer-1229/ERROR] [Sponge]: /*     net.minecraft.world.WorldServer.func_180501_a(WorldServer.java:4520)                                   */
[21:06:43] [Timer-1229/ERROR] [Sponge]: /*     com.mrtrollnugnug.ropebridge.handler.BridgeBuildingHandler.buildBridge(BridgeBuildingHandler.java:227) */
[21:06:43] [Timer-1229/ERROR] [Sponge]: /*     com.mrtrollnugnug.ropebridge.handler.BridgeBuildingHandler.access$100(BridgeBuildingHandler.java:19)   */
[21:06:43] [Timer-1229/ERROR] [Sponge]: /*     com.mrtrollnugnug.ropebridge.handler.BridgeBuildingHandler$2.run(BridgeBuildingHandler.java:232)       */
[21:06:43] [Timer-1229/ERROR] [Sponge]: /*     java.util.TimerThread.mainLoop(Timer.java:555)                                                         */
[21:06:43] [Timer-1229/ERROR] [Sponge]: /*     java.util.TimerThread.run(Timer.java:505)                                                              */
[21:06:43] [Timer-1229/ERROR] [Sponge]: /**************************************************************************************************************
**
So it only placed the first block and can not handle the others. 
Is it possible to fix that and release the fix also for 1.12?

By the way: The zooming when placing the bridge also doesn't work.
Thanks

**Comment by KiriCattus** [comment] 2021-05-31 04:41
Dupe of #25, will close and when a fix is found close that issue too.

**Closed as completed by KiriCattus** 2021-05-31 04:41 UTC
Labels: duplicate, 1.12
